### ISSUE TITLE
Wrong behaviour with accent letters

### ISSUE THREAD

**Issue by SebastienBoisard** [c-bata/go-prompt#10]
Hi c-bata,

Thanks a lot for go-prompt, it helps me a lot. :+1: 

It might not be important for english people, but there is a problem with accent letters on go-prompt.
In fact, when I enter an word with an accent, like "voilà", in the echo program, the cursor go back to the 'à' letter after typing it. 
As a result, go-prompt is not very usable for french people, for example.

Thanks for your help.

**Comment by c-bata** [comment]
Thanks for reporting.
This problem is also happened on my environment.
But what accounts for this problem haven't been understand yet.
I'll debug with the logfile. If I fixed, I'll comment here.

**Comment by SebastienBoisard** [comment]
The problem seems to be here: https://github.com/c-bata/go-prompt/blob/master/render.go#L151

```go 
  // r.out.CursorBackward(len(line) - buffer.CursorPosition)
  // Using rune, it works.
  r.out.CursorBackward(len([]rune(line)) - buffer.CursorPosition)

```
You are using the length of a string, but you need the length of a rune, because an accent character is stored in more than one byte.

The number of character is "été" (summer in french) is 3, but len("été") is 5.

You can try here: https://play.golang.org/p/lqnWRP1H7w

I hope this helps.

**Comment by c-bata** [comment]
So Thanks @SebastienBoisard! I didn't notice it.
Now I merge a your patch at:
https://github.com/c-bata/go-prompt/commit/b825471eb8e00fd28c93e128068b36ce0b447a47

So your problem is fixed on current master branch.

<img width="244" alt="2017-09-06 3 19 59" src="https://user-images.githubusercontent.com/5564044/30076073-b91ddfe8-92b2-11e7-890c-df603851e404.png">

**Comment by c-bata** [comment]
Actually CJK problem still exist on current master branch.
go-prompt should calculate the length of Japanese Kanji as 2 length. But the length of rune array is 1.
For example:

```
gore> len([]rune("日本語"))
3
```

So I need to calculate the length of "日本語" as 6 characters.
I have a plan to fix this problem by using [mattn/go-runewidth](https://github.com/mattn/go-runewidth).
