### ISSUE TITLE
Support functions which will expose the setter for this variable, because this will help in writing the test-cases for the framework

### ISSUE THREAD

**Issue by shreyassreenivas** [c-bata/go-prompt#109]
https://github.com/c-bata/go-prompt/blob/63e3a6f38aca443ea14c57bf6cde497a6ebd4062/document.go#L17

**Comment by shreyas165** [comment]
Hi Masashi,
Sorry if this is a lame question,
I am trying to implement a test cases around the completion handler completer, And the completer takes Document as the parameter and the whole logic is written around it.
Basically I am trying to write the test-cases written similarly in go-prompt project itself [document_test.go].
Can you pls let me know how can I achieve this state of the Document {Text:hi,cursorPosition:2}

**Comment by c-bata** [comment]
Sorry I don't understand what you said. Your question means that how you write tests around Document struct from outside of go-prompt package? It sounds an anti-pattern of unit testing.

**Comment by shreyas165** [comment]
Sorry, I found a way to go ahead with my test cases using buffers as you suggested

**Comment by gustavodemorais** [comment]
An example if someone ends up here:

```
buffer := prompt.NewBuffer()
buffer.InsertText("some text", false, false) // last parameter moves cursor automatically
buffer.CursorRight(2) // you can also do it manually
```
