### ISSUE TITLE
Problem with key bindings

### ISSUE THREAD

**Issue by SebastienBoisard** [c-bata/go-prompt#11]
I have some problems adding key bindings in go-prompt.
I took the 'echo' example, and tried to add a simple print for the 'Home', 'End' and 'PageUp' keys, but only the 'Home' key bind worked:

```go
package main

import (
	"fmt"
	"github.com/c-bata/go-prompt"
)

func executor(in string) {
	fmt.Println("Your input: " + in)
}

func completer(in prompt.Document) []prompt.Suggest {
	s := []prompt.Suggest{
		{Text: "users", Description: "Store the username and age"},
		{Text: "articles", Description: "Store the article text posted by user"},
		{Text: "comments", Description: "Store the text commented to articles"},
		{Text: "groups", Description: "Combine users with specific rules"},
	}
	return prompt.FilterHasPrefix(s, in.GetWordBeforeCursor(), true)
}

func main() {
	p := prompt.New(
		executor,
		completer,
		prompt.OptionPrefix(">>> "),
		prompt.OptionTitle("sql-prompt"),
		prompt.OptionAddKeyBind(prompt.KeyBind{
			Key: prompt.Home,
			Fn: func(buf *prompt.Buffer) {
				fmt.Println("HOME")
			}}),
		prompt.OptionAddKeyBind(prompt.KeyBind{
			Key: prompt.End,
			Fn: func(buf *prompt.Buffer) {
				fmt.Println("END")
			}}),
		prompt.OptionAddKeyBind(prompt.KeyBind{
			Key: prompt.PageUp,
			Fn: func(buf *prompt.Buffer) {
				fmt.Println("Up")
			}}),
	)
	p.Run()
}
```

What's wrong with my code?

Thanks for your help.

PS: by the way, the default behaviour of the 'Home' key doesn't take into account the length of the Prefix (here, the ">>>").

**Comment by c-bata** [comment]
Thanks.
I'm currently investigating.

**Comment by SebastienBoisard** [comment]
There might be some errors in yours keys `asciiSequences` defintions.

For example, here : https://github.com/c-bata/go-prompt/blob/master/vt100_input.go#L146

```
	{Key: End, ASCIICode: []byte{0x1b, 0x5b, 0x70}},
	{Key: End, ASCIICode: []byte{0x1b, 0x4f, 0x70}},
````

If you replace 0x70 by 0x46, it works for the 'End' key.

I replaced 0x05 by 0x35, and 0x06 by 0x36 for PageUp and PageDown, and it works:

```
	{Key: PageUp, ASCIICode: []byte{0x1b, 0x5b, 0x35, 0x7e}},
	{Key: PageDown, ASCIICode: []byte{0x1b, 0x5b, 0x36, 0x7e}},
```

**Comment by c-bata** [comment]
Hi, @SebastienBoisard!
These definition of ascii sequences is migrated from python-prompt-toolkit like:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/4476b3c28add85c5a8169fbb81ded8c3b845e588/prompt_toolkit/terminal/vt100_input.py#L92-L93

`End` key is properly migrated from python-prompt-toolkit.

But as you said, the ascii sequences of `PageUp` and `PageDown` seems to be wrong.
The ascii sequence of `5` is `0x35` and also `6` is `0x36`.

https://github.com/jonathanslenders/python-prompt-toolkit/blob/4476b3c28add85c5a8169fbb81ded8c3b845e588/prompt_toolkit/terminal/vt100_input.py#L99-L100

I'll fix. Thanks!

**Comment by c-bata** [comment]
This issue is fixed on current master branch.

https://github.com/c-bata/go-prompt/blob/43889dc4a6a7835267bb5e23abc734858a59ca13/vt100_input.go#L155-L156

I'll close this. Thanks!!

**Comment by SebastienBoisard** [comment]
Hi @c-bata,

From the python-prompt-toolkit, you have this:
```
    '\x1b[H': Keys.Home,
    '\x1bOH': Keys.Home,
    '\x1b[F': Keys.End,
    '\x1bOF': Keys.End,
```
and you migrated these keys in Go with:
```
	{Key: Home, ASCIICode: []byte{0x1b, 0x5b, 0x48}},
	{Key: Home, ASCIICode: []byte{0x1b, 0x4f, 0x48}},
	{Key: End, ASCIICode: []byte{0x1b, 0x5b, 0x70}},
	{Key: End, ASCIICode: []byte{0x1b, 0x4f, 0x70}},
```
The last value for the 'Home' key is 'H' in Python which you properly translated to 0x48.
But the last value for the 'End' key is 'F' in Python which is not 0x70 but 0x46.

So, I'm pretty sure that the correct code for the 'End' key is this one:  :wink: 
```
	{Key: End, ASCIICode: []byte{0x1b, 0x5b, 0x46}},
	{Key: End, ASCIICode: []byte{0x1b, 0x4f, 0x46}},
```

Thanks for your help.

**Comment by c-bata** [comment]
Oh I missed 😫 
I fixed this at https://github.com/c-bata/go-prompt/commit/76a3a211c326c002bb8cffc07334f39f8c49e9c1

<img width="367" alt="2017-09-17 18 43 20" src="https://user-images.githubusercontent.com/5564044/30519720-2a5d68a8-9bd8-11e7-8da6-6e93f506b217.png">

**Comment by SebastienBoisard** [comment]
Great! :smile: 

Thanks a lot for your help.
