### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by brettbuddin** [c-bata/go-prompt#12]
I'm encountering a data race during my debug sessions with `-race`. I'm performing a simple `prompt.New(...).Run()` and then typing into the prompt to trigger this behavior.

### Race Detection Trace

```
...
> patch:apply()
WARNING: DATA RACE
Write at 0x00c4200b8400 by goroutine 13:
  internal/race.WriteRange()
      /usr/local/Cellar/go/1.9/libexec/src/internal/race/race.go:49 +0x42
  syscall.Read()
      /usr/local/Cellar/go/1.9/libexec/src/syscall/syscall_unix.go:165 +0x9a
  buddin.us/lumen/vendor/github.com/c-bata/go-prompt.readBuffer()
      /Users/brettbuddin/Code/src/buddin.us/lumen/vendor/github.com/c-bata/go-prompt/prompt.go:262 +0x11d

Previous read at 0x00c4200b8400 by main goroutine:
  runtime.slicebytetostring()
      /usr/local/Cellar/go/1.9/libexec/src/runtime/string.go:72 +0x0
  buddin.us/lumen/vendor/github.com/c-bata/go-prompt.(*Prompt).feed()
      /Users/brettbuddin/Code/src/buddin.us/lumen/vendor/github.com/c-bata/go-prompt/prompt.go:169 +0x1761
  buddin.us/lumen/vendor/github.com/c-bata/go-prompt.(*Prompt).Run()
      /Users/brettbuddin/Code/src/buddin.us/lumen/vendor/github.com/c-bata/go-prompt/prompt.go:70 +0x5e7
  buddin.us/lumen/lua.repl()
      /Users/brettbuddin/Coexit status 66
```

### Points of Interest

1. Write to buffer before sending a slice of it over a channel: https://github.com/c-bata/go-prompt/blob/b825471eb8e00fd28c93e128068b36ce0b447a47/prompt.go#L262
2. Receive the slice from the channel and then operate on it: https://github.com/c-bata/go-prompt/blob/b825471eb8e00fd28c93e128068b36ce0b447a47/prompt.go#L70
3. The `[]byte` that's being shared between goroutines is being allocated here: https://github.com/c-bata/go-prompt/blob/b825471eb8e00fd28c93e128068b36ce0b447a47/prompt.go#L252

I'm going to take a crack at fixing this and will open a PR soon-ish, but I just wanted to file an issue just in case anyone else isn't aware of it.

This library has really helped me out so far. Thanks for it. Cheers 🍻

**Comment by c-bata** [comment]
Hi @brettbuddin !

Sorry for my late reply. This issue must be fixed.
I'm waiting for your PR.

Thanks :)

**Comment by brettbuddin** [comment]
I've been using this branch in my project for a bit now. Seems to have solved the problem.

**Comment by c-bata** [comment]
Sorry for my late response.
I can reproduce this problem now and confirmed that this is fixed by your PR.
Thanks!
