### ISSUE TITLE
Add nested go-prompt functionality

### ISSUE THREAD

**Issue by manojakondi** [c-bata/go-prompt#127]
## Expected Behavior

Based on the command at top level prompt, I want to create a child go-prompt. Is there anyway we can add nested go-prompt functionality? at least up to 2 levels.

Like in the image below.
<img width="701" alt="Screen Shot 2019-03-09 at 1 14 14 AM" src="https://user-images.githubusercontent.com/15820209/54051806-aeb85b80-4208-11e9-8276-3913bc9bc4ea.png">

**Comment by c-bata** [comment]
You can change prefix string via https://godoc.org/github.com/c-bata/go-prompt#OptionLivePrefix

The example is below:

https://github.com/c-bata/go-prompt/tree/master/_example#live-prefix

**Comment by manojakondi** [comment]
@c-bata Thank you for the prompt response. My requirement is to have a 2 level prompt in my application. Once I enter into my cli, based on the command given at the top level, I want to get into a new go-prompt instance with the given command as a Live Prefix. 

But my question is not just to have prefix. But also to have 2 different functionalities inside each prompt. Is it possible?

**Comment by c-bata** [comment]
So you want to change the `completer` and `executor` in one prompt, right? It is possible by storing the state like:

https://github.com/c-bata/go-prompt/blob/df16feb8c1cbf7cffd957596d8428fe5b2a4c738/_example/live-prefix/main.go#L9-L12

```
package main

import (
	"fmt"

	prompt "github.com/c-bata/go-prompt"
)

var yourAppState struct {
	subcommand string
	LivePrefix string
	IsLivePrefixEnable   bool
}

func executor(in string) {
	if yourAppState.subcommand == "" {
		// 1 level prompt
	} else if yourAppState.subcommand == "cases" {
		// 2 level prompt
	}
}

func completer(in prompt.Document) []prompt.Suggest {
	if yourAppState.subcommand == "" {
		// 1 level prompt
	} else if yourAppState.subcommand == "cases" {
		// 2 level prompt
	}
}

func changeLivePrefix() (string, bool) {
	return yourAppState.LivePrefix, yourAppState.IsLivePrefixEnable
}

func main() {
	p := prompt.New(
		executor,
		completer,
		prompt.OptionPrefix(">>> "),
		prompt.OptionLivePrefix(changeLivePrefix),
	)
	p.Run()
}
```
