### ISSUE TITLE
Project using go-prompt (abs-lang)

### ISSUE THREAD

**Issue by mingwho** [c-bata/go-prompt#133]
Hello there,

We are working on a new scripting language using go-prompt, and we want to add it to "Projects using go-prompt" session.

[ABS is a scripting language that works best on terminal. It tries to combine the elegance of languages such as Python, or Ruby, to the convenience of Bash.](https://github.com/abs-lang/abs)

Thanks for this amazing lib 👍

**Comment by c-bata** [comment]
Amazing! I added abs at https://github.com/c-bata/go-prompt/commit/ea6035601114c4fb96ea02b79935762df24a99e5
