### ISSUE TITLE
Project using go-prompt (btcli) 

### ISSUE THREAD

**Issue by takashabe** [c-bata/go-prompt#134]
Hi, I created a Cloud Bigtable client `btcli` using `go-prompt` .
https://github.com/takashabe/btcli

Could you add this to `Projects using go-prompt` list in the README?

Thanks for an amazing library :+1:

**Comment by c-bata** [comment]
Awesome! I've just added your project at https://github.com/c-bata/go-prompt/commit/e697e0224d6571276c4560232f4c2a9642e82cb5
