### ISSUE TITLE
Exit command does not work on http-prompt example

### ISSUE THREAD

**Issue by dgarana** [c-bata/go-prompt#136]
PR already waiting for review: #135

# Bug reports

If someone try to run the http-prompt example provided, he will never be able to execute the "exit" command successfully (basically because there's no implementation for it)

## Expected Behavior

Whenever you input "exit" on the prompt, the application should stop with exit code 0.

## Current Behavior and Steps to Reproduce

If someone execute the "exit" command, the application will do nothing.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOSX
* Terminal Emulator: iTerm2
* tag of go-prompt or commit revision: 1.12.6

**Comment by c-bata** [comment]
Thank you!
