### ISSUE TITLE
An auto-completion kafka-prompt using go-prompt

### ISSUE THREAD

**Issue by ysn2233** [c-bata/go-prompt#138]
Hi, I created a kafka command line prompt based on your fantastic framework. Would you mind putting my project [kafka-prompt](https://github.com/ysn2233/kafka-prompt) on the frontpage list?

**Comment by c-bata** [comment]
Good job! I added kafka-prompt at 6b41a41 👍

**Comment by c-bata** [comment]
BTW, I found two typos on your repository.

1. s/"A interactive"/"An interactive"

![スクリーンショット 2019-07-08 21 21 28](https://user-images.githubusercontent.com/5564044/60809820-8cd6e180-a1c6-11e9-8ff1-e52383cd2728.png)

2. s/usign/using

![スクリーンショット 2019-07-08 21 23 33](https://user-images.githubusercontent.com/5564044/60809872-abd57380-a1c6-11e9-8ddf-7f46947faa22.png)
