### ISSUE TITLE
example project list - yet another tool using go-prompt

### ISSUE THREAD

**Issue by fishi0x01** [c-bata/go-prompt#144]
I recently wrote [vsh](https://github.com/fishi0x01/vsh) which is relying on go-prompt for auto-completion. If you see it as a reasonable example it would be cool to see it on the example project list.

_Quick summary of the tool:_
vsh is an interactive shell wrapper around the HashiCorp Vault client. It allows common operations such as `cp`, `rm`, `mv` to work recursively on paths. 
The go-prompt completion is used to auto-complete the path navigation and list available commands.

**Comment by c-bata** [comment]
Sorry for my late reply and Thank you for creating cool project. I'll add vsh in the project using go-prompt section later.

**Comment by c-bata** [comment]
vsh is added at 97fbae6. Thanks!
