### ISSUE TITLE
How to return the execution back to the caller

### ISSUE THREAD

**Issue by zWaR** [c-bata/go-prompt#152]
In my case go-prompt is just a part of application and I would like to do something like this:

```go
func main() {
  myPrompt := prompt.New()
  myPrompt.Run()

// some other logic, executed once prompt returns
}
```
Any hints on how to do that are welcome!

**Comment by ksbickmore** [comment]
if you haven't found an answer for this yet, try looking at the exit checker option. I've done worked with this in my module at https://gitlab.com/kbickmore/go-cmd

**Comment by zWaR** [comment]
Hey @ksbickmore,

I changed the application architecture, so that I did not need to do what I mentioned in the OP. Thanks for the reply and the pointer, though.
