### ISSUE TITLE
"panic: runtime error: integer divide by zero" - getting error on docker container

### ISSUE THREAD

**Issue by harshapic** [c-bata/go-prompt#17]
Try to run this on docker container getting error

panic: runtime error: integer divide by zero, any help please?

**Comment by c-bata** [comment]
Hi @harshapic ! Could you tell me your source code using go-prompt.
I can't help you without it.

**Comment by harshapic** [comment]
yes its using go-prompt

 /home/sdp/go/src/github.com/xxxxx/sdp-cli-client/vendor/github.com/c-bata/go-prompt/prompt.go:50 +0xe0
main.main()
        /home/sdp/go/src/github.com/xxxxx/sdp-cli-client/main.go:78 +0x764

Tried to run on docker container with base "ubuntu:16.04"
docker version: Docker version 17.03.2-ce, build f5ec1e2

**Comment by harshapic** [comment]
import (
	"fmt"

	"github.com/c-bata/go-prompt"
)

Actually if i run it on ubuntu machine my code is working fine when i copy executable to docker container and if i try to run it it giving me error

**Comment by c-bata** [comment]
Sorry, It's difficult to help you from these information.
Is `sdp-cli-client` your private project? I need to check the source code and need to know how you use go-prompt.

**Comment by harshapic** [comment]
ok let me create a test project and create docker container with it and will give you source code

**Comment by harshapic** [comment]
this is my sample test project, it has everything even with dockerfile.
Steps to replicate issue:

1) CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o yang-cli
2) docker build -t yang-cli .
3) docker run -it yang-cli /bin/sh

[yang-cli.tar.gz](https://github.com/c-bata/go-prompt/files/1368101/yang-cli.tar.gz)

**Comment by harshapic** [comment]
you will get this issue:

yangcli  (rev-)
Please use `exit` or `Ctrl-D` to exit this program..
Bye!
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/yang-cli/vendor/github.com/c-bata/go-prompt.(*Render).Render(0xc4200d6000, 0xc420069d80, 0xc4200cc810)
        /home/sdp/go/src/github.com/yang-cli/vendor/github.com/c-bata/go-prompt/render.go:134 +0x50c
github.com/yang-cli/vendor/github.com/c-bata/go-prompt.(*Prompt).Run(0xc42008bce0)
        /home/sdp/go/src/github.com/yang-cli/vendor/github.com/c-bata/go-prompt/prompt.go:50 +0xe0
main.main()
        /home/sdp/go/src/github.com/yang-cli/main.go:44 +0x5a3

**Comment by harshapic** [comment]
but same thing it works properly on my developer machine

**Comment by harshapic** [comment]
@c-bata  ru able to reproduce issue on docker container?

**Comment by bcicen** [comment]
This is kind of a race condition between the time taken for docker to complete allocation of psuedo terminal and go-prompts initial window calculations.

Fix submitted in https://github.com/c-bata/go-prompt/pull/32

**Comment by c-bata** [comment]
thank you @bcicen
