### ISSUE TITLE
[Bug] Usage of Ctrl+C binding corrupt STTY settings

### ISSUE THREAD

**Issue by sattellite** [c-bata/go-prompt#176]
# Bug reports

## Expected Behavior

After my program is finished with `ControlC` binding, I expect that <kbd>Ctrl</kbd>+<kbd>C</kbd> combination will work in the terminal as it did before the program launch.

## Current Behavior and Steps to Reproduce

After finished my program by `ControlC` binding and <kbd>Ctrl</kbd>+<kbd>C</kbd> combination do nothing.

```go
p := prompt.New(
	// ... other options
	prompt.OptionAddKeyBind(prompt.KeyBind{
		Key: prompt.ControlC,
		Fn: func(b *prompt.Buffer) { os.Exit(0) }
	}),
)

p.Run()
```

If I send text command to _executor_ for exit it calls `os.Exit(0)` too and program finished correctly.

Program exit if I press Ctrl+C in opened prompt and stty settings is corrupted.

I got settings before run program with `stty -a > stty.before` and after finish program by CTRL+C with `stty -a > stty.after`. 

```diff
--- stty.before	2020-05-26 15:30:40.827199004 +0300
+++ stty.after	2020-05-26 15:30:47.212105711 +0300
@@ -3,8 +3,8 @@
 eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
 werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
 -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
--ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
+-ignbrk -brkint ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff
 -iuclc -ixany imaxbel iutf8
 opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig icanon -iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
+-isig icanon -iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
 echoctl echoke -flusho -extproc
```

Disabled this options: -brkint -icrnl -ixon -isig

Option **isig** enable interrupt, quit, and suspend special characters. 

More info about stty https://linux.die.net/man/1/stty

For restore initial behavior need use command `reset`.

## Context

* Operating System: Fedora Linux, CentOS
* Terminal Emulator: gnome-terminal
* commit revision: d043be07639872dd59e161726523dcf4687959cc

**Comment by chriswalz** [comment]
Is there a workaround for this?

**Comment by sattellite** [comment]
> Is there a workaround for this?

I using my CLI command with reset after it, but this is ugly hack
`my-cli-command && reset`

**Comment by sattellite** [comment]
Found workaround in [chriswalz/bit](https://github.com/chriswalz/bit). Code sample [here](https://github.com/chriswalz/bit/blob/7cda500d0ed637c014c6347b67a6496e6296c12e/cmd/util.go#L231-L251).

At begin of programm add defered exit handler with `recover`. Deferred function calls are executed in Last In First Out order. It will be called by the most recent. And bind a function with `panic` to ControlC combination.

```golang
...
func main() {
	defer handleExit()
	p := prompt.New(
		// ... other options
		prompt.OptionAddKeyBind(prompt.KeyBind{
			Key: prompt.ControlC,
			Fn: exit
		}),
	)

	p.Run()
}

type Exit int

func exit(_ *prompt.Buffer) {
	panic(Exit(0))
}

func handleExit() {
        v := recover()
	switch v.(type) {
	case nil:
		return
	case Exit:
		os.Exit(int(v))
	default:
		fmt.Printf("%+v", v)
	}
}
...
```

**Comment by josephspurrier** [comment]
MR: https://github.com/c-bata/go-prompt/pull/239 resolves this problem. The code sample above no longer works.
