### ISSUE TITLE
[Bug] Garbled characters when running go-prompt over serial

### ISSUE THREAD

**Issue by benaranguren** [c-bata/go-prompt#179]
# Bug reports

*Please file a bug report here.*

## Expected Behavior

Opening go-prompt over serial connection should display characters just like when I run it over ssh or telnet.

## Current Behavior and Steps to Reproduce

1. Connect to a remote host via serial
2. Launch a program using go-prompt.
3. Notice the unreadable characters instead of a prompt.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux
* Terminal Emulator: (i.e. minicom)
* tag of go-prompt or commit revision: c8c75cc295ca66affff899dba2c452667e65b9e5

**Comment by c-bata** [comment]
Thank you!
