### ISSUE TITLE
[Feature Request] Add a new project in README

### ISSUE THREAD

**Issue by rueyaa332266** [c-bata/go-prompt#184]
# Feature Request

Hi, @c-bata I created a CLI tool using go-prompt.
I'm wondering if you can add this project in the README.
https://github.com/rueyaa332266/ezcron

It's a CLI that helps to deal with cron expression.
And it also my first open source project on Github. 
Maybe it still have a lot place can improve, but I have a good time working with go-prompt.
Thank you for creating a wonderful prompt library.

**Comment by c-bata** [comment]
Great work 👍  I added ezcron at 667e20b.
