### ISSUE TITLE
Detect exit request with CTRL-D in Input

### ISSUE THREAD

**Issue by TzahiFadida** [c-bata/go-prompt#189]
# Feature Request

# Feature Request

Hi, thank you for the lovely library.
I am using it in a project here https://github.com/fortify500/stepsman
Would appreciate if you can add me to the list.
Currently I am using Input and not Run because I have no apparent way to enter the OptionInitialBufferText on every input (which i need).
However, the biggest problem is that in Input I don't know if a CTRL-D was pressed to exit. I tried serval tricks like KeyBind (which is not triggered for some reason) but to no avail.

Would appreciate it if it was possible to somehow either detect CTRL-D after the Input finished like an err returned in addition to the string or a callback or simply enter "exit" string.

Thanks!

**Comment by TzahiFadida** [comment]
I would add that I tried the exitchecker but CTRL-D exits before getting to it, not that it would help as it is, it always provides breakline false (at least on my build) for some reason.

**Comment by TzahiFadida** [comment]
Managed to do something like 
prompt.OptionAddKeyBind(prompt.KeyBind{
					Key: prompt.ControlM,
					Fn: func(buffer *prompt.Buffer) {
						wasEnter = true
					},
				})
if the returned input is "" and wasEnter=false then i am guessing CTRL-D was pressed. Not sure if it is valid ...

**Comment by mpokryva** [comment]
If I understand correctly, you implemented your own `exit` command, yes? If so, you can use the executor to detect this:


```
var exitCalled bool

func(in string) {
    if in == "exit" {
        exitCalled = true
}
```
Somewhere else in your program:
```
func foo() {
prompt.Run()
if exitCalled {
        fmt.Println("exited with `exit` cmd")
} else {
        fmt.Println("exited with `Ctrl-D`")

If that's the only other method of exiting, then that should work.

**Comment by TzahiFadida** [comment]
@mpokryva thank you for the reply.
However, please note I am using the prompt.Input().
Run() does not have that issue. I am using the Input() to have full control.

Thanks.

**Comment by mpokryva** [comment]
Whoa, sorry, I have no idea how I missed that. That was dumb. I think your approach is valid. I'm using v0.2.3, the latest tag, but it looks like master behaves the way https://github.com/c-bata/go-prompt/blob/56c224c88aba4d7326e30211b5a29d816a5cd42d/prompt.go#L123. If `Enter, ControlJ, ControlM` are pressed, then `Input()` returns. I think your approach will be more comprehensive if you add those keys as well.
