### ISSUE TITLE
Supports scrollbar when there are too many matched suggestions 

### ISSUE THREAD

**Issue by piglei** [c-bata/go-prompt#19]
Now, we can only set a max suggestions count to limit the total suggestions. If it was set to 10 when there are 20 matches, only the first 10 items will be shown.

While python-prompt-toolkit can display the prompt popup with a scrollbar in the right side, so user can choose from all matched items by scroll up and down.

pic of python-prompt-toolkit:

![](https://github.com/jonathanslenders/python-prompt-toolkit/raw/master/docs/images/ptpython.png)

**Comment by c-bata** [comment]
This feature is added by @orisano.  Thanks.
