### ISSUE TITLE
Project using go-prompt (bit) 

### ISSUE THREAD

**Issue by chriswalz** [c-bata/go-prompt#199]
Hello, we are working on an experimental git cli replacement called bit and would love to see our project added to the "Projects using go-prompt" list.

bit is a Modernized Git CLI. https://github.com/chriswalz/bit

Many thanks!

**Comment by c-bata** [comment]
Cool! I added Bit at https://github.com/c-bata/go-prompt/commit/8e6eb48b4aa09bfc6701ad171e6c855d873724a3.
