### ISSUE TITLE
How to bind ctrl+c to terminate current running command?

### ISSUE THREAD

**Issue by FrontMage** [c-bata/go-prompt#20]
Hi, I've been using this lib building a dynamodb prompt, it's all good until I try to kill a query running too long.
Ctrl+c seems can't kill what is running in that executor function, so I looked up in the docs, but can't find any useful tips.

Can someone help me with this, thanks~~

**Comment by FrontMage** [comment]
I can only use the second method, but after pressing `ctrl+c` does not trigger cancel.

It inputs some `^C` instead, so my cancel function is not being triggered.

Still working on it.

**Comment by c-bata** [comment]
OK. I'll prepare sample code for canceling pattern via context package.

**Comment by FrontMage** [comment]
@c-bata After some digging I found a way to do this.

I can't use the build-in keybindings of go-prompt, because while the executor is running, the channel select function is blocked.

So I just have to create another goroutine listening to `os.Interrupt` then use cancel function to cancel the running query, which is another goroutine.

The main executor function will have to wait until `ctx.Done()` so that new lines won't popup.

Code is like below:
```
		ctx, cancel := context.WithCancel(context.Background())
		c := make(chan os.Signal, 1)
		signal.Notify(c, os.Interrupt)
		go func() {
			select {
			case <-c:
				cancel()
			}
		}()
		go func() {
			defer cancel()
			if sqlparser.SelectRegexp.MatchString(s) {
				// add surfix "END" for rexexp matching
				executors.Select(s + " END")
			}
			if sqlparser.DescRegexp.MatchString(s) && sqlparser.TableRegexp.MatchString(s) {
				executors.DescribeTable(s + " END")
			}
			// TODO require WHERE field, update all seems not so safe?
			if sqlparser.UpdateRegexp.MatchString(s) {
				executors.Update(s + " END")
			}
			// TODO support SHOW TABLE
		}()
		select {
		case <-ctx.Done():
			return
		}
```

Thanks for the help, sir, looking forward to see more awesome prompts built with this.

**Comment by tangximing** [comment]
the signal os.Interrupt is also been trapped by build-in keybindings of go-prompt

**Comment by figuremout** [comment]
It's due to SetRaw() set syscall.ISIG negative [here](https://github.com/c-bata/go-prompt/blob/82a912274504477990ecf7c852eebb7c85291772/internal/term/raw.go#L22), which prevents ctrl-c to generate signal, [more about termios settings](https://man7.org/linux/man-pages/man3/termios.3.html)
My solution is to keep the original termios settings before `(*prompt.Prompt).Run()` changing it, and restore the original settings in executor to enable ctrl-c, then use the way that @FrontMage mentioned to catch the signal.
Here is a runnable example:
```golang
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	"github.com/c-bata/go-prompt"
	"github.com/pkg/term/termios"
	"golang.org/x/sys/unix"
)

var fd int
var originalTermios *unix.Termios

func Executor(input string) {
	// restore the original settings to allow ctrl-c to generate signal
	if err := termios.Tcsetattr(uintptr(fd), termios.TCSANOW, (*unix.Termios)(originalTermios)); err != nil {
		panic(err)
	}

	if input == "test" {
		ctx, cancel := context.WithCancel(context.Background())
		c := make(chan os.Signal, 1)
		signal.Notify(c, os.Interrupt)

		go func() {
			select {
			case <-c:
				cancel()
			}
		}()
		go func() {
			defer cancel()
			for { // long task
			}
		}()
		select {
		case <-ctx.Done():
			return
		}
	}
}
func completer(d prompt.Document) []prompt.Suggest {
	s := []prompt.Suggest{}
	return prompt.FilterHasPrefix(s, d.GetWordBeforeCursor(), true)
}

func main() {
	var err error
	fd, err = syscall.Open("/dev/tty", syscall.O_RDONLY, 0)
	if err != nil {
		panic(err)
	}
	// get the original settings
	originalTermios, err = termios.Tcgetattr(uintptr(fd))
	if err != nil {
		panic(err)
	}

	p := prompt.New(Executor, completer)

	p.Run()
}
```
