### ISSUE TITLE
[Bug] Library doesn't work with latest version of github.com/pkg/term

### ISSUE THREAD

**Issue by creekorful** [c-bata/go-prompt#206]
Hello there!

Little issue to let you know that your package doesn't work anymore when using with latest version of github.com/pkg/term.

I have written a patch to fix that, and can create a PR (with go module refactoring) if you are willing to review + merge it.

Would you be interested?

**Comment by c-bata** [comment]
Thank you for reporting.

It sounds like a quite serious issue.
I'm welcome for your pull request. I'll merge it and release the new version.

**Comment by creekorful** [comment]
Uh-oh, sorry mate I've just noticed that it's my fault, I was running an outdated version of go-prompt. 
Just tested with latest and everything works.

Nevermind, and sorry!
