### ISSUE TITLE
Closing the terminal?

### ISSUE THREAD

**Issue by SUMUKHA-PK** [c-bata/go-prompt#207]
`Ctrl-C` doesnt close the terminal, found that `Ctrl-D` closes it but that too doesnt seem to work.
How do I close the terminal? :D

**Comment by c-bata** [comment]
Yes, Ctrl-C does not close the prompt like it does not close bash shell.
But Ctrl-D closes thee prompt if the buffer is empty.

I guess you pressed `Ctrl-D` after input something characters.

```
>>> <Ctrl-D> # then prompt will be closed.
```

```
>>> input something values<Ctrl-D> # then prompt won't be closed because the buffer is not empty.
```

These behaviors are the same with bash shell.

Let me close this issue. If Ctrl-D doesn't work even if the buffer is empty. I'm welcome to file a bug report.
