### ISSUE TITLE
populate Suggest iteratively

### ISSUE THREAD

**Issue by gennaro-tedesco** [c-bata/go-prompt#226]
## Help wanted
Unclear statement on how to populate Suggestion list iteratively

## Context
Referring to the [docs here](https://github.com/c-bata/go-prompt#go-prompt) and [here](https://pkg.go.dev/github.com/c-bata/go-prompt?utm_source=godoc#Suggest) I am trying to populate
```
s := []prompt.Suggest{
		{Text: "users", Description: "Store the username and age"},
		{Text: "articles", Description: "Store the article text posted by user"},
		{Text: "comments", Description: "Store the text commented to articles"},
	}
```
iteratively, instead of specifying the items one by one. In particular, my use case is to populate the suggestion list with the keys of a `map[string]interface{}`. Whenever I try to access and populate the field `s.Text` I get an error 

> `s.Text undefined (type []prompt.Suggest has no field or method Text)` 

although the structure `Suggest` does possess `Text` as property, does it not?

Do we have a shorthand grammar to do so?

**Comment by dshelley66** [comment]
In the example above s is an array of Suggest. In order to access the Text field in one of the Suggest elements you need to index into the array - s[0].Text

**Comment by gennaro-tedesco** [comment]
You are right, thank you for the clarification!
