### ISSUE TITLE
this library doesn't support Windows?

### ISSUE THREAD

**Issue by niciyan** [c-bata/go-prompt#23]
When i run 'got get' for this library, I got message below
```
# github.com/pkg/term/termios
..\..\pkg\term\termios\pty.go:20: undefined: open_pty_master
..\..\pkg\term\termios\pty.go:25: undefined: Ptsname
..\..\pkg\term\termios\pty.go:30: undefined: grantpt
..\..\pkg\term\termios\pty.go:35: undefined: unlockpt
```

My environment
OS: Windows 10
version:
  go version go1.8.3 windows/amd64

I want to try go-prompt.
Please help!

**Comment by c-bata** [comment]
go-prompt has just supportem windows at a following PR.
https://github.com/c-bata/go-prompt/pull/31

**Comment by niciyan** [comment]
Finally we got windows support.
Great work.

Thanks.
