### ISSUE TITLE
gRPC client using go-prompt

### ISSUE THREAD

**Issue by ktr0731** [c-bata/go-prompt#26]
hi, I created a gRPC client, [Evans](https://github.com/ktr0731/evans).  
thanks for go-prompt, it was able to realize more convenient user interface! 😄 
could you add this tool to "Projects using go-prompt" in the README?

**Comment by c-bata** [comment]
Good job @ktr0731 ! A gRPC client using go-prompt is much needed.
https://github.com/c-bata/go-prompt/commit/95fb1dd6f46bb6fd222e42eaac1ae92a77c5ca28
