### ISSUE TITLE
feature request: Allow binding of any key

### ISSUE THREAD

**Issue by nemith** [c-bata/go-prompt#42]
# Suggestions

It's very common on routing platforms like Cisco IOS or Juniper Junos that the ? will instantly return context sensitive help.  To get a real question mark you do a CTRL-V.   The existing key bindings seem to be only for modifiers + keys.  It would be nice to be able to bind any key at the prompt.

**Comment by c-bata** [comment]
This feature is implemented at https://github.com/c-bata/go-prompt/pull/65.
Thanks.
