### ISSUE TITLE
Rendering issue: `?` is invisible while typing.

### ISSUE THREAD

**Issue by Allajah** [c-bata/go-prompt#43]
# Bug reports

## Expected Behavior

`?` have to be rendered properly.

## Current Behavior and Steps to Reproduce
`?` is invisible while typing. You can see on a following GIF.
![feb-15-2018 05-30-44](https://user-images.githubusercontent.com/5627119/36226565-83eb7af4-1211-11e8-932a-5ddf2727f266.gif)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: macOS 10.12.6
* Terminal Emulator: iTerm2
* tag of go-prompt or commit revision: `7c05c0763ad15c362f3636e02624e84b2a43c902`

**Comment by unasuke** [comment]
reproduced it on my ubuntu 17.10 at the same revision (tmux on gnome-termianl)

![screenshot from 2018-02-15 09-50-25](https://user-images.githubusercontent.com/4487291/36235750-bfa04664-1235-11e8-87ba-f306a9a2e486.png)
