### ISSUE TITLE
Way to exit prompt?

### ISSUE THREAD

**Issue by gcstang** [c-bata/go-prompt#46]
# Suggestions

Ability to exit the prompt using Ctrl+C or something else in the examples without having to kill the terminal window.
i.e. Ctrl+C, etc...
---

* Operating System: Mac OS El Capitan
* Terminal Emulator:  iTerm2
* tag of go-prompt or commit revision: latest head version

**Comment by c-bata** [comment]
You can quit via Control+D.

**Comment by lucasalcantara** [comment]
@c-bata Currently my program exits when I use Ctrl + C and I'd like to know if I can put the prompt to do the same instead of exit via Ctrl + D
