### ISSUE TITLE
Customize insertion point for completion suggestions

### ISSUE THREAD

**Issue by apparentlymart** [c-bata/go-prompt#53]
Thanks for this library! It's impressive how quickly it's possible to get a REPL-like program working with it. I ran into a problem with a program I'm working on. Possibly there is already a way to solve this that I just didn't find yet, but in case that's not true...

# Suggestions

I'm working on a REPL-like program that evaluates expressions in an expression language which contains the usual arithmetic operators, functions, variables, etc. As part of this I want to support autocomplete for variable names and object attribute names.

I have some examples working already:

```
> obj = {foo = "foo", bar = "bar"}

> ob
(suggests "obj")

> obj.
(suggests "obj.foo", "obj.bar")

> obj.fo
(suggests "obj.foo")

> complex = [{foo = "foo", bar = "bar"}, {"foo" = "foo", "notbar" = "notbar"}]

> complex[0].
(suggests "complex[0].foo" and "complex[0].bar")

> complex[1].
(suggests "complex[1].foo" and "complex[1].notbar")

> obj.foo + obj.
(suggests "obj.foo" and "obj.bar")
```

I run into problems, though, if the user doesn't use whitespace around the operators:

```
> obj.foo+obj.
(suggests "obj.foo" and "obj.bar" as expected, but when a suggestion is accepted
the entire input is replaced with it)
```

From studying the code I think I see why it behaves in this way:

https://github.com/c-bata/go-prompt/blob/f329ebd2409de559ba256325b8a18b13a145b5d5/prompt.go#L166-L170

Although my program is using `d.TextBeforeCursor()` and using its own simple scanner to recognize the start of the complete-able expression, the insertion code seems to be fixed using `.GetWordBeforeCursor()`, which then sees `obj.foo+obj.` as a single word, because "words" are defined as being space-separated.

Ideally I'd like to somehow be able to give the completer a "hint" about which portion of the document each suggestion is intended to replace. My completion callback already knows a byte offset into the `.GetWordBeforeCursor()` result which it could potentially return.

Alternatively, I could potentially implement another callback (using similar logic) that could replace the built-in `FindStartOfPreviousWord` as an option, effectively repeating the scanning operation my completion callback is already doing to find the start of the current expression.

A new field on type `Suggest` to give that offset hint would be most convenient for my use-case, but I'm sure there are complexities here I don't know, and so I'd be grateful for any reasonable feature to meet this use-case, if you agree it's worth addressing.

At the moment I'm just working on a toy prototype, but if I can get good results with the prototype (which I have so far, this quirk aside!) then my work here may be adapted into a more practical application with similar needs.

Thanks!

**Comment by c-bata** [comment]
Thanks for submitting this issue. go-prompt doesn't support such a feature yet. Actually I thought 
a same thing when implementing local files completer at kube-prompt:
https://github.com/c-bata/kube-prompt/pull/14

So I know this feature is needed. As you said the implementation is a little complex, but I want to provide something solution for this issue.

**Comment by c-bata** [comment]
Hi @apparentlymart! This feature is implemented at https://github.com/c-bata/go-prompt/pull/79

**Comment by apparentlymart** [comment]
Thanks, @c-bata! My focus has shifted elsewhere for the moment, but it looks like I should be able to adapt my prototype to support this by making a string containing all of the language's punctuation characters as additional separators.
