### ISSUE TITLE
Are there any methods to highlight the input?

### ISSUE THREAD

**Issue by godbcli** [c-bata/go-prompt#54]
### Is there any methods to highlight the input?
I know `prompt.OptionInputTextColor(prompt.Blue)` can be used to highlight the input,
but it only has one color.
If i want to highlight the input(e.g. SQL) language, 
is there any methods to achieve?

**Comment by c-bata** [comment]
Sorry I forgot to reply this issue. There isn't such a feature because it's a little bit complex.

**Comment by doronbehar** [comment]
Hey!

I was about to open a feature request for this feature and I've found this one. [Python-prompt-toolkit provides this feature using pygments](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/tutorials/repl.html#syntax-highlighting). It seems natural that go-prompt will provide this feature using [chroma](https://github.com/alecthomas/chroma).

@c-bata do you think it'll be a little bit easier to implement using chroma?
