### ISSUE TITLE
Completion on non space separated words

### ISSUE THREAD

**Issue by nlewo** [c-bata/go-prompt#61]
I would like to bring completion on a language where words (or lexical identifiers) of an expression are not separated by spaces. For instance, consider the following expression:
```
object.method(value)
```
where `object` can have several available methods.

I would like to be able to do
```
object.<tab><tab>
``` 
to get the list of method and select a method among this list.

Is it currently possible? And is there an example somewhere?
Thanks.

**Comment by c-bata** [comment]
Thanks for submitting. this is duplicate with https://github.com/c-bata/go-prompt/issues/53

**Comment by c-bata** [comment]
This feature is implemented at #79
