### ISSUE TITLE
Suggestion to add example for list selection

### ISSUE THREAD

**Issue by geocine** [c-bata/go-prompt#62]
# Suggestions

Please add more examples. I wanted to know how to create a list selection where I can navigate with up/down arrow keys.

**Comment by c-bata** [comment]
I think a following example is enough to know your question:
https://github.com/c-bata/go-prompt/blob/master/_example/echo/main.go

**Comment by geocine** [comment]
thanks @c-bata  , I am talking about something like this. Is this possible?

![select options](https://i.imgur.com/1fcZA7d.jpg)

**Comment by c-bata** [comment]
I see. go-prompt doesn't provide such a feature.
go-prompt just support following completion.

![kube-prompt](https://github.com/c-bata/assets/raw/master/go-prompt/kube-prompt.gif)

So when you want to use such a completion, please use survey or promptui.

* https://github.com/AlecAivazis/survey
* https://github.com/manifoldco/promptui

**Comment by geocine** [comment]
thanks @c-bata
