### ISSUE TITLE
Move cursor one word left or right

### ISSUE THREAD

**Issue by Chyroc** [c-bata/go-prompt#63]
# Suggestions

Please write your suggestion here and removed "Bug reports section".

in  ： https://stackoverflow.com/questions/6205157/iterm-2-how-to-set-keyboard-shortcuts-to-jump-to-beginning-end-of-line

i can change iTerm2 setting: 
* `0x1b 0x62` to Move cursor one word left
* `0x1b 0x66 ` to Move cursor one word right

how can i do this same with go-prompt

* Operating System:
osx

* Terminal Emulator:
iTerm2

* tag of go-prompt or commit revision:
master

**Comment by Chyroc** [comment]
the answer of stackoverflow says is to set such key, not the real key.

**Comment by Chyroc** [comment]
i make a pr , and  add the follow code in my project to move cursor one word left or right
```
		prompt.OptionAddASCIICodeBind(prompt.ASCIICodeBind{
			ASCIICode: []byte{0x1b, 0x62},
			Fn: func(buffer *prompt.Buffer) {
				prompt.GoLeftWord(buffer)
			},
		}),
		prompt.OptionAddASCIICodeBind(prompt.ASCIICodeBind{
			ASCIICode: []byte{0x1b, 0x66},
			Fn: func(buffer *prompt.Buffer) {
				prompt.GoRightWord(buffer)
			},
		}),
```

**Comment by chriswalz** [comment]
Thank you @chyroc this is super helpful for `bit` CLI!
