### ISSUE TITLE
Library using go-prompt: moshpit

### ISSUE THREAD

**Issue by CrushedPixel** [c-bata/go-prompt#73]
I've written [*moshpit*](https://github.com/CrushedPixel/moshpit), a command-line tool to perform datamoshing, using `go-prompt`:
![tutorial](https://i.imgur.com/XGrR2Kv.gif)

Thank you so much for your amazing tool, it made creating a helpful command line interface easy as pie!
If you want, please include my tool in your list of tools using `go-prompt` :)

**Comment by c-bata** [comment]
This looks interesting. I added moshpit at b966724.
Thanks.
