### ISSUE TITLE
Bug with cyrillic

### ISSUE THREAD

**Issue by DeadNumbers** [c-bata/go-prompt#75]
Hi! After changing the keyboard layout to Russian cursor stands still, moving along the line <-> does not work, instead I move the cursor to the right with the space key.

![prompt](https://user-images.githubusercontent.com/9416005/41203975-32e51f4e-6cce-11e8-8c40-7ddb5982f670.gif)

* Operating System: Arch Linux
* Terminal Emulator: bug seen in xterm, termite, terminator
* tag of go-prompt or commit revision: df30f172f3303e37022ab7f89854ef1965e9fb43

**Comment by c-bata** [comment]
Thank you reporting 👍 
This is a known problem. Currently, go-prompt doesn't support not only Russian but also Japanese and zero/double width characters. I have a plan to fix these issues.

**Comment by c-bata** [comment]
Hi @DeadNumbers! I fixed this issue at https://github.com/c-bata/go-prompt/pull/77
