### ISSUE TITLE
Is it possible to perform validation?

### ISSUE THREAD

**Issue by akiross** [c-bata/go-prompt#8]
I used go-prompt successfully to implement input with completion, but in my application I also need to ask input and validate it. I was wondering if it is possible to use the go-prompt infrastructure to force a valid input (for example, input matching a regex).

Naturally, I am not talking about doing that in a loop (input -> validate -> ask again), but I would like to do that inline, as user type.

**Comment by c-bata** [comment]
HI @akiross !
Thanks for using go-prompt.

This library is golang porting of python-prompt-toolkit and it does not have such a feature.
So I think your proposal feature is not bad but now I have no plan to implement a something validation.
Please validate user input at your application like:

```
package main

import (
    "fmt"

    "github.com/c-bata/go-prompt"
)

func completer(in prompt.Document) []prompt.Suggest {
    s := []prompt.Suggest{
        {Text: "users", Description: "Store the username and age"},
        {Text: "articles", Description: "Store the article text posted by user"},
        {Text: "comments", Description: "Store the text commented to articles"},
        {Text: "groups", Description: "Combine users with specific rules"},
    }
    return prompt.FilterHasPrefix(s, in.GetWordBeforeCursor(), true)
}

func validate(s string) bool {
    return s != ""
}

func main() {
    valid := false
    for {
        in := prompt.Input(">>> ", completer, prompt.OptionTitle("sql-prompt"))
        if validate(in) {
            break
        }
        fmt.Println("Please input a something table name.")
    }
    fmt.Println("Your input: " + in)
}
```

**Comment by akiross** [comment]
Oh, thanks. I was not aware this package was a *port* and I thought it was *inspired* to python-prompt-toolkit.

Anyway, I am interested in having a better validation method, so I will study a bit the library internals and see if I can come up with a solution. In that case, I will do a PR.
