### ISSUE TITLE
Add way to exit go-prompt

### ISSUE THREAD

**Issue by fhemberger** [c-bata/go-prompt#9]
Either it's well hidden or there doesn't seem to be a way to exit go-prompt.
Tried `Ctrl-C`, `Ctrl-X`, `Esc`, `exit`, `quit` in kube-prompt …

**Comment by c-bata** [comment]
Hi @fhemberger!
Thank you for using kube-prompt.
The answer is Ctrl-D. But maybe it is a little hard to notice.

Hmm... I'll support a quit or exit command.
Thanks!

**Comment by c-bata** [comment]
Hmm... I think the default behavior of go-prompt should be 
By implementing `exit` or `quit` command in go-prompt, it may be conflict with something features.
For example, kube-prompt supports `kubectl exec` command. By using this, we can login to the container managed by kubernetes like:

```
$ kube-prompt
>>> exec -it <pod name> bash  # login to the container.
bash-$ pwd
/home/foo
bash-$ exit  # logout
>>> 
```

In this pattern, the `exit` command means the logout. So the user doesn't want to quit kube-prompt. So now I think `exit` and `quit` command should be implemented in kube-prompt like:

```
func completer(d prompt.Document) []prompt.Suggest {
    // returns something suggestions.
}

func executor(in string) {
    if in == "exit" {
        // quit this program.
    }
    // execute something command.
    return
}

func main() {
    pt := prompt.New(executor, completer)
    pt.Run() 
}
```

**Comment by c-bata** [comment]
I decided the go-prompt doesn't provide other way to exit and this problem on kube-prompt is fixed like:
https://github.com/c-bata/kube-prompt/issues/7

If you want to add the way to exit, please refer following changes:
https://github.com/c-bata/kube-prompt/commit/e3ab4f4152825e94ff2027c380aee2050bc2ca31

Thanks.
