### ISSUE TITLE
Input example is leaving the console with colored text

### ISSUE THREAD

**Issue by sandipb** [c-bata/go-prompt#93]
# Suggestions

When I run `go run src/github.com/c-bata/go-prompt/_example/echo/main.go` the console ends up with bold text in my iterm and my xterm terminals.

---

# Bug reports

It seems like Render.Teardown is not resetting the default colors on exit. Please let me know if I am mistaken:

```go
 // TearDown to clear title and erasing.                                                         |   -livePrefixCallback : func() string,
 func (r *Render) TearDown() {                                                                   |   -out : ConsoleWriter
     r.out.ClearTitle()                                                                          |   -prefix : string
     r.out.EraseDown()                                                                           |   -prefixBGColor : Color
     r.out.Flush()                                                                               |   -prefixTextColor : Color
 }                                                                                               |   -previewSuggestionBGColor : Color
```

Should this not also include `r.out.SetColor(DefaultColor, DefaultColor, false)`?

## Expected Behavior

The console to be back to its previous text formatting after `prompt.Input()` finishes.

## Current Behavior and Steps to Reproduce

1. `go get -u github.com/c-bata/go-prompt`
2. `go run src/github.com/c-bata/go-prompt/_example/echo/main.go`

*What is the current behavior? Please provide detailed steps for reproducing the issue.*

If you enter your own string, the program exits as expected - with previous console colors. However, if you accept the suggestions, the program exits with bold text.

[![asciicast](https://asciinema.org/a/MyAk4oLNfOelrHQDSTub0YTzj.png)](https://asciinema.org/a/MyAk4oLNfOelrHQDSTub0YTzj)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Mac OSX High Sierra
* Terminal Emulator: iTerm2 and xquartx terminal
* tag of go-prompt or commit revision: HEAD

**Comment by sandipb** [comment]
It seems #85 is fixing this for me.

**Comment by c-bata** [comment]
Awesome. This report is easy to understand. I'll fix this.
