### ISSUE TITLE
Support for readline-like reverse search

### ISSUE THREAD

**Issue by nirbhayc** [c-bata/go-prompt#96]
# Suggestions

* Add support for readline-like reverse search through the history.
```
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print "foo"
foo
>>> print "bar"
bar
(reverse-i-search)`print': print "bar"
```

**Comment by rhtyd** [comment]
@c-bata can you advise? Thanks.

**Comment by c-bata** [comment]
Good suggestion. I wanna add this feature if go-prompt keeps simple implementation.

**Comment by c-bata** [comment]
duplicate with https://github.com/c-bata/go-prompt/issues/96
